version: 3.0.{build}
branches:
  only:
  - DotNetCore
image: Visual Studio 2017
configuration: Release
environment:
  nodejs_version: 7.8.0
install:
- ps: Install-Product node $env:nodejs_version
cache: '%USERPROFILE%\.nuget\packages'
before_build:
- ps: .\BuildTask.ps1 -env "live"
- cmd: cd src/ombi
- node --version
- appveyor-retry dotnet restore
- appveyor-retry npm install bower -g
- appveyor-retry npm install -g gulp
- appveyor-retry npm install
- gulp publish
build:
  parallel: true
after_build:
- dotnet publish -c Release -r ubuntu.16.04-x64
- cmd: >-
    7z a Ombi_ubuntu.zip %APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcoreapp1.1\ubuntu.16.04-x64\publish

    appveyor PushArtifact Ombi_ubuntu.zip
deploy:
- provider: GitHub
  release: Ombi v$(appveyor_build_version)
  auth_token: 8aef0140318039cd1b8aea9b1cccbf48536c9b59
  draft: true
  on:
    branch: DotNetCore
